openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaMind app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaMind app
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: Operations about user.
  - name: Water
    description: Water operations.
servers:
  - url: https://aqua-mind.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /user:
    get:
      $ref: '../swagger/paths/user/get.yaml'
    patch:
      $ref: '../swagger/paths/user/patch.yaml'
  /user/photo:
    patch:
      $ref: '../swagger/paths/user/photo/patch.yaml'
  /user/water-rate:
    get:
      $ref: '../swagger/paths/water-rate/get.yaml'
    patch:
      $ref: '../swagger/paths/water-rate/patch.yaml'
  /water/today:
    get:
      $ref: '../swagger/paths/today/get.yaml'
  /water/month/{year}/{month}:
    get:
      $ref: '../swagger/paths/month/get.yaml'
  /water:
    post:
      $ref: '../swagger/paths/water/post.yaml'
  /water/{waterId}:
    patch:
      $ref: '../swagger/paths/water/{waterId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/water/{waterId}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
