openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaMind app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaMind app
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: Operations about user.
  - name: WaterRate
    description: Calc of daily water intake.
  - name: Water
    description: Water operations.
  - name: Today
    description: Information about water consumption per day.
  - name: Month
    description: Information about water consumption per month.
servers:
  - url: http://localhost:3000
  - url: https://aqua-mind.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /user/{userId}:
    get:
      $ref: '../swagger/paths/user/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/user/{id}/patch.yaml'
  /user/{userId}/photo:
    patch:
      $ref: '../swagger/paths/user/{id}/photo/patch.yaml'
  /water-rate:
    get:
      $ref: '../swagger/paths/water-rate/get.yaml'
    patch:
      $ref: '../swagger/paths/water-rate/patch.yaml'
  /today:
    get:
      $ref: '../swagger/paths/today/get.yaml'
  /month:
    get:
      $ref: '../swagger/paths/month/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
